config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index]
      end
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :likes
  has_many :posts
  has_many :comments

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts(count: 3)
    posts.order(created_at: :desc)[0, count]
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authorize!, only: %i[index show], if: :user_signed_in?

  def index
    json_response({ message: 'Welcome' }, 404)
  end

  def show
    json_response({ message: 'to see the posts' }, 404)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @all_posts = @user.recent_posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_tile.html.erb
<% stylesheet_link_tag 'users/index' %>

<%= link_to user do %>
<div class="flex m-5 h-32 gap-5">
    <div class="w-32 h-full object-cover">
        <img src="<%= user.photo %>" alt="Profile Picture">
    </div>
    <div id="box-border" class="m-3 p-5 flex flex-col justify-center">
        <h1 class="font-black self-end"><%= user.name %></h1>
        <p class="text-lg self-end">Number of Posts: <%= user.posts_counter || 0 %></p>
    </div>
</div>
<% end %>

app/views/users/index.html.erb
<div class="p-10">
  <ul class="list-none flex flex-col gap-5">
    <% @users.each do |user| %>
      <li>
        <%= render 'users/user_tile', user: user %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<% stylesheet_link_tag 'users/index' %>
<div class="p-10 flex flex-col gap-7">
  <%= render 'users/user_tile', user: @user %>
  <div id="box-border" class="p-4 flex flex-col gap-4 border-solid">
    <p class="text-base font-bold">Bio</p>
    <p><%= @user.bio %></p>
    <%= link_to new_user_post_path(@user) do %>
      <button id="box-border">Create a new Post</button>
    <% end %>
  </div>
   <ul>
    <% @all_posts.each do |post| %>
      <li>
          <%= render 'posts/post_tile', post: post, user:@user, expanded: false %>
      </li>
    <% end %>
  </ul>
  <div class="flex justify-center">
    <%= link_to user_posts_path(@user) do %>
      <button id="box-border" class="h-10 w-32 cursor-pointer">See all posts</button>
    <% end %>
  </div>
  <%=form_with model: User.new, url: destroy_user_session_path, method: :delete do %> <button class="custom-button">Sign out</button>
        <% end %>
</div>