config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index]
      end
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :update_counter

  def update_counter
    user.update(posts_counter: user.posts.count)
  end

  def recent_comments(count: 5)
    comments.order(created_at: :desc)[0, count]
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize!, only: %i[index show], if: :user_signed_in?

  def index
    @posts = Post.all

    if @posts.empty?
      json_response({ message: 'Posts not found' }, 404)
    else
      render json: @posts, status: :ok
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @all_posts = @user.posts.includes(:comments).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = current_user
    post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: } }
    end
  end

  def create
    @user = current_user
    post = Post.new(post_params)
    post.user_id = @user.id
    post.comments_counter = 0
    post.likes_counter = 0
    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'Post created!'
          redirect_to user_posts_path(@user)
        else
          flash.now[:error] = 'Post not created!'
          render :new, locals: { post: }
        end
      end
    end
  end

  def destroy
    @user = current_user
    post = Post.find(params[:id])

    if post.destroy
      flash[:success] = 'Post deleted!'
      redirect_to user_posts_path(@user)
    else
      flash.now[:error] = 'Post not deleted!'
      redirect_to user_posts_path(@user, post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments_tile.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="box-border" class="p-4">
  <ul class="flex flex-col gap-1">
    <% comments.each do |comment| %>
      <li class="flex gap-3">
        <p class="font-semibold"><%= comment.user.name %>:</p>
        <p class="text-sm"><%= comment.text %></p>
        <% if can? :destroy, comment %>
          <%= form_with url: user_post_comment_path(@user, @post, comment), method: :delete do %>
            <button type="submit" class="h-10 w-32 cursor-pointer">Delete</button>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% if comments.length == 0 %>
    <p>No Comments yet</p>
  <% end %>
</div>

app/views/posts/_expanded_post_tile.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="box-border" class="p-4 flex flex-col gap-7">
  <div class="flex space-x-4 justify-between">
    <h2 class="text-xl"><%= post.title %></h2>
    <div class="flex flex-row gap-5">
      <p>Comments <%= post.comments_counter || 0 %></p>
      <p>Likes <%= post.likes_counter || 0 %></p>
    </div>
  </div>
  <p><%= post.text %></p>
  <div class="flex self-end gap-1">
    <% if can? :destroy, @post %>
      <% form_with url: user_post_path(@user, @post), method: :delete do %>
        <button type="submit" class="h-10 w-32 cursor-pointer">Delete</button>
      <% end %>
    <% end %>
  <%= link_to new_user_post_comment_path @user, @post do %>
    <button class="h-10 w-32 cursor-pointer">Comment</button>
  <% end %>
  <%= form_with model: Like.new, url: user_post_likes_path(@user, @post), method: :post do %>
    <button class="h-10 w-32 cursor-pointer">Like</button>
  <% end %>
  </div>
</div>

app/views/posts/_post_tile.html.erb
<% stylesheet_link_tag 'users/index' %>

<%= link_to user_post_path(user, post) do %>
<div id="box-border" class="p-4 flex flex-col">
  <h2 class="text-lg mb-4"><%= post.title %></h2>
  <p class="overflow-hidden whitespace-nowrap text-ellipsis"><%= post.text %></p>
  <div class="lex gap-5 self-end">
    <p>Comments <%= post.comments_counter || 0 %></p>
    <p>Likes <%= post.likes_counter || 0 %></p>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<% stylesheet_link_tag 'users/index' %>
<div class="p-10 flex flex-col gap-7">
  <%= render 'users/user_tile', user: @user %>
  <div class="mt-0 mr-auto ">
    <%= link_to new_user_post_path(@user) do %>
      <button id="box-border" class="p-4 cursor-pointer h-12">Create a new Post</button>
    <% end %>
  </div>
  <ul class="list-none flex flex-col gap-7">
    <% @all_posts.each do |post| %>
      <li>
        <%= render 'posts/post_tile', post: post, user: @user, expanded: false %>
        <%= render 'posts/comments_tile', comments: post.recent_comments %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<% stylesheet_link_tag 'users/index' %>
<div id="add-new-page" class="flex flex-col items-center gap-16 p-10">
  <h1 class="pb-1">Create a New Post</h1>
  <%= form_with model: post, url: user_posts_path(@user), method: :post, local: true do |form| %>
    <%= form.text_field :title, placeholder: 'Enter Title' %>
    <%= form.text_area :text, rows: 10, placeholder: "Enter post " %>
    <%= form.submit "Submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="flex flex-col p-10">
  <%= render 'posts/expanded_post_tile', post: @post %>
  <%= render 'posts/comments_tile', comments: @post.comments %>
</div>